language: cpp
dist: xenial
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt512base libgl1-mesa-dev qt512svg qt512imageformats
  - source /opt/qt*/bin/qt*-env.sh  
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  
  - # Generate AppImage
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - export VERSION=$(git rev-parse --short HEAD)
  - mv ../default.desktop .
  - mv ../icon.png .
  - ./linuxdeployqt*.AppImage ./CPEditor -appimage 
  - curl --upload-file ./CP_Editor*.AppImage https://transfer.sh/CPEditor-git.$(git rev-parse --short HEAD)-x86_64.AppImage 

# Temporarily disabled so that AppImage generation can be tested
# branches:
#   only:
#    - master
