blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://github.com/cpeditor/cpeditor#faq
    about: You may find your question and the answer here.
  - name: Manual
    url: https://github.com/cpeditor/cpeditor/blob/master/doc/MANUAL.md
    about: Some instructions and tips.
  - name: Telegram Group
    url: https://t.me/cpeditor
    about: You can ask questions except for feature requests and bug reports here.
  - name: Slack Workspace
    url: https://join.slack.com/t/cpeditor/shared_invite/zt-dke1v9xd-zr~QeXJhCzbM9FFOjx6sMA
    about: You can ask questions except for feature requests and bug reports in the "help" channel.
