name: "Check Clang Format"

on:
  push:
    paths-ignore:
      - '*.md'
      - '*/*.md'
      - '*/*/*.md'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*/*.md'
      - '*/*/*.md'

jobs:
  format:
    name: "Check Clang Format"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Install clang-format-9"
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-9
    - name: "Format Codes"
      run: clang-format-9 -i src/*.cpp src/*/*.cpp src/*.hpp src/*/*.hpp
    - name: Check diff
      run: git diff --exit-code HEAD
